Grafdatabasen/Controllers/GrafController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Grafdatabasen.Controllers
{
    public class GrafController : Controller
    {
        // GET: Graf
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search()
        {
            ViewBag.Message = "Detta är då söksidan...";

            return View();
        }

        public ActionResult Write()
        {
            ViewBag.Message = "Här är inmatningssida 1.";

            return View();
        }

    }
}

Grafdatabasen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Kompetensdatabasen</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/bootstrap-datepicker.min.css")
    @Styles.Render("~/Content/select2.css")
    @Scripts.Render("~/Scripts/jquery-2.1.3.min.js")
    @Scripts.Render("~/Scripts/typeahead.bundle.js")
    @Scripts.Render("~/Scripts/Ajaxneo4j.js")






    <style>
        .modal-content {
            width: 900px !important;
            margin: 30px auto !important;
        }
       
    .twitter-typeahead .tt-query,
.twitter-typeahead .tt-hint {
	margin-bottom: 0;
}
.tt-hint {
	display: block;
	width: 100%;
	height: 38px;
	padding: 8px 12px;
	font-size: 14px;
	line-height: 1.428571429;
	color: #999;
	vertical-align: middle;
	background-color: #ffffff;
	border: 1px solid #cccccc;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
	      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
	-webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
	      transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}
.tt-dropdown-menu {
	min-width: 160px;
	margin-top: 2px;
	padding: 5px 0;
	background-color: #ffffff;
	border: 1px solid #cccccc;
	border: 1px solid rgba(0, 0, 0, 0.15);
	border-radius: 4px;
	-webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
	      box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
	background-clip: padding-box;
 
}
.tt-suggestion {
	display: block;
	padding: 3px 20px;
}
.tt-suggestion.tt-is-under-cursor {
	color: #fff;
	background-color: #428bca;
}
.tt-suggestion.tt-is-under-cursor a {
	color: #fff;
}
.tt-suggestion p {
	margin: 0;
}

    </style>

</head>
<body>
    <div class="container-fluid">
    </div>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kompetensdatabasen", "Index", "Graf", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Graf", "Index", "Graf")</li>
                    <li>@Html.ActionLink("Sök", "Search", "Graf")</li>
                    <li>@Html.ActionLink("Lägg till/Ändra", "uppdrag", "Write")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Brandt &amp; Thiel </p>
        </footer>*@

    </div>

    <div id="modal-container" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>

    @*Scripts.Render("~/Scripts/jquery-2.1.3.min.js")*@
    @Scripts.Render("~/Scripts/modernizr-2.8.3.js")
    @Scripts.Render("~/Scripts/select2.js")
    @Scripts.Render("~/Scripts/bootstrap.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.min.js")
    @Scripts.Render("~/Scripts/locales/bootstrap-datepicker.sv.min.js")

    <script type="text/javascript">
        $(document).ready(function () {

            $('.date').datepicker({
                format: "yyyy-mm-dd",
                weekStart: 1,
                language: "sv",
                orientation: "top auto",
                keyboardNavigation: false,
                autoclose: true,
                todayHighlight: true,
                startDate: "2002-01-01"
            });

            $(function () {
                // Initialize numeric spinner input boxes
                //$(".numeric-spinner").spinedit();
                // Initialize modal dialog
                // attach modal-container bootstrap attributes to links with .modal-link class.
                // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
                $('body').on('click', '.modal-link', function (e) {
                    e.preventDefault();
                    $(this).attr('data-target', '#modal-container');
                    $(this).attr('data-toggle', 'modal');
                });
                // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
                $('body').on('click', '.modal-close-btn', function () {
                    $('#modal-container').modal('hide');
                });
                //clear modal cache, so that new content can be loaded
                $('#modal-container').on('hidden.bs.modal', function () {
                    $(this).removeData('bs.modal');
                });
                $('#CancelModal').on('click', function () {
                    return false;
                });
            });
        })
    </script>


    </body>
</html>

<script type="text/javascript">
    //$(document).ready(function () {
        var ajaxgraf = ajaxneo4j("match path= (n) return  n");
        //console.log(ajaxgraf.responseJSON.results[0].data);
        sessionStorage.setItem('nodes', JSON.stringify(ajaxgraf.responseJSON.results[0].data));
        
    //});
</script>